title: Temporary Moments
author: Ellen Duong and Angela Schwartz

# Serving
port: 8000

sass:
  style: compressed

exclude:
  - .idea/
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - INSTRUCTIONS.md
  - README.md
  - Spectral_README.txt
  - credentials.json
  - node_modules
  - package-lock.json
  - package.json
  - requirements.txt
  - token.pickle
  - update_photos.py
  - venv/
  - webpack.config.js
  - scripts/